name: Simple Docker Test

on:
  release:
    types: [published]
  push:
    tags:
      - "v*"
  workflow_dispatch:

env:
  REGISTRY: registry.thedondon.org
  IMAGE_NAME: dondon-developments

jobs:
  test-build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Personal Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Echo environment
        run: |
          echo "Registry: ${{ env.REGISTRY }}"
          echo "Image: ${{ env.IMAGE_NAME }}"
          echo "Tag: ${{ github.ref_name }}"
          echo "Event: ${{ github.event_name }}"

      - name: Test Docker build (no push)
        run: |
          echo "Would build Docker image here"
          echo "This is just a test - no actual build"
